name: flutter_slds_icons_example
description: flutter_slds_icons example app.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slds_icons:
    # When depending on this package from a real application you should use:
    #   flutter_slds_icons: ^x.y.z
    path: ../

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
