name: flutter_slds_icons
description: An icon pack derived from the Salesforce Lightning Design System icons.
version: 1.1.0
repository: https://github.com/mj12358/flutter-slds-icons

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: SLDSIcons
      fonts:
        - asset: lib/assets/SLDSIcons.ttf
