name: flutter_slds_icons
description: An icon pack derived from the Salesforce Lightning Design System icons.
version: 0.0.2
repository: https://github.com/mj12358/flutter-slds-icons

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: SLDSIcons
      fonts:
        - asset: lib/assets/SLDSIcons.ttf
