name: flutter_slds_icons
description: An icon pack derived from the Salesforce Lightning Design System icons.
version: 2.0.0
repository: https://github.com/mj12358/flutter-slds-icons
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - flutter
  - icons
  - salesforce
  - slds
  - sfdx

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: SLDSIcons
      fonts:
        - asset: lib/assets/SLDSIcons.ttf
